### ISSUE TITLE
sort an array using bubble sort

### ISSUE THREAD

**Issue by soumy47** [soumy47/Data-Structures-Algorithms-in-C#6]
Goto algorithm ->sorting.c

**Comment by ManasDroid** [comment]
Please assign this to me @soumy47  !

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer in C language and recently i am pursuing b tech in computer science engeneering branch . (2 year)

**Comment by soumy47** [comment]
It has been already solved,  you can try out other stuff.
