### ISSUE TITLE
anagram of a string 

### ISSUE THREAD

**Issue by soumy47** [soumy47/Data-Structures-Algorithms-in-C#8]
Goto string->anagram.c

**Comment by ManasDroid** [comment]
I want to work on this

**Comment by Agung-Krisna** [comment]
I want to try to complete this issue, please assign this to me

**Comment by soumy47** [comment]
Hey ,

> I want to try to complete this issue, please assign this to me
Hey @Agung-Krisna , @ManasDroid  has completed this issue. 
You can create PR to add more programs.
